const reasons = [
"I love the way you always know how to make me feel better, even when I get anxious over small things, or sleep on the floor for an hour."
"Your thoughtfulness and empathy always amazes me, and I feel so lucky to have you in my life."
"I admire how hard you work and I appreciate every hour you put in to improve yourself, even when you dont want to."
"I love the way you listen to me ramble (for instance about book plots), you always make me feel heard and understood."
"You can make me laugh about the stupidest things, and i appreciate that."
"I’m constantly inspired by your kindness and how you treat others with so much respect (i.e. the Rimi donation incident)."
"I love how you always find ways to make me feel appreciated and loved - like getting me little treats from the shop."
"You motivate me to become better every day."
"I admire your ability to stay calm under pressure; you’re my rock in difficult times (even if I'm the one causing the difficult times sometimes)."
"The way you support me unconditionally - even through my tiktok era - means the world to me."
"I love how you push me to be the best version of myself while always accepting me as I am (and also reminding me that I do in fact need rest)."
"I appreciate the honesty and integrity you have shown towards me (even if you sometimes still wanna be a lil secretive, but manage to be transparent <3)."
"I love how we can talk about anything, and it always feels like time stands still."
"Your smile has a way of making everything better, no matter what’s going on."
"I love the time we both spend watching tv-shows - even if I fall asleep after 15 minutes"
"Your strength and resilience are incredible, I see you toughing it out through bad times and I think youre amazing."
"I love how your presence alone makes me feel safe and secure - even through home break ins."
"You always make me laugh, even when I don’t feel like smiling."
"I love the way you take care of yourself and encourage me to do the same (i.e. telling me to take a shower)."
"I love talking with you about everything, it helps me see things in a new light."
"I love how we challenge each other to grow and learn together (i.e. you tell me to not go to gym, whilst I tell you to go to gym)."
"You’re always so generous and I appreciate that more than you know - its my favorite quality of yours"
"I admire the way you handle challenges with such calm and determination - even if sometimes I find it hard to stay calm woth you."
"I love how you can make even the simplest moments feel special - everything feels amazing with you, even grocery shopping."
"Your curiosity about the world and your willingness to explore new things reminds me of my own wishes to learn every day."
"I love how we can always find some joy together, even in tough situations."
"You make me feel so so so loved when you take care of me."
"I love how you (pretty much) always know the right words to say to make me feel better."
"I find it very cute how immersed you get whilst playing video-games (even if I would prefer the volume to be a bit lower)."
"I love the way you always put others first, even when you’re busy or stressed."
"Your ability to make me feel at ease, no matter the situation, is something I cherish."
"I love how you’ve taught me to approach life with a positive and calm mindset - its something I really need with how anxious I am."
"You’re the first person I want to share my successes with, because you genuinely celebrate them with me."
"I love how you always go above and beyond to make me feel loved and valued."
"Your thoughtfulness in the little things always brings a smile to my face."
"I admire the way you take care of everyone around you and I adore your gentleness."
"I love how we balance each other out and make the perfect team <3"
"Your attention to detail is something I always appreciate."
"I love the way you’re always there when I need support, no questions asked."
"Your love and affection always make me feel like the luckiest person in the world."
"I admire how patient and understanding you are, especially when I need it the most (and am throwing tiny lil tantrums)."
"I love how you always bring a sense of peace and calm into my life."
"Your ability to see the best in people is something I really admire about you (I also love when you get a little mean when it comes to people who have done me wrong)."
"I love the way you care for our relationship and always make it a priority."
"I appreciate every time you take care to calm me down and help me when I am feeling down - you are my support."
"I love how you make everything feel like an adventure, even the most mundane things."
"Your support means everything to me, and I’m so grateful for it every day."
"I love how we create our own little world together here in Milan, even if we do miss Latvia."
"Your  belief in me gives me the courage to pursue my ambitions and chase things like PhD programmes and article submissions."
"You make life better simply by being in it <3"
];

function generateReason() {
    const randomIndex = Math.floor(Math.random() * reasons.length);
    document.getElementById("reason").textContent = reasons[randomIndex];
}
